/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.devraccoon.starcraft.domain.game;
@org.apache.avro.specific.AvroGenerated
public enum GameType implements org.apache.avro.generic.GenericEnumSymbol<GameType> {
  FourVsFour, OneVsOne, ThreeVsThree, TwoVsTwo  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"GameType\",\"namespace\":\"com.devraccoon.starcraft.domain.game\",\"symbols\":[\"FourVsFour\",\"OneVsOne\",\"ThreeVsThree\",\"TwoVsTwo\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
