/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.devraccoon.starcraft.domain.server;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PlayerIsLookingForAGame extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -9107965821609437355L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PlayerIsLookingForAGame\",\"namespace\":\"com.devraccoon.starcraft.domain.server\",\"fields\":[{\"name\":\"eventTime\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"playerId\",\"type\":{\"type\":\"string\",\"logicalType\":\"UUID\"}},{\"name\":\"gameType\",\"type\":{\"type\":\"enum\",\"name\":\"GameType\",\"namespace\":\"com.devraccoon.starcraft.domain.game\",\"symbols\":[\"FourVsFour\",\"OneVsOne\",\"ThreeVsThree\",\"TwoVsTwo\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<PlayerIsLookingForAGame> ENCODER =
      new BinaryMessageEncoder<PlayerIsLookingForAGame>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PlayerIsLookingForAGame> DECODER =
      new BinaryMessageDecoder<PlayerIsLookingForAGame>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PlayerIsLookingForAGame> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PlayerIsLookingForAGame> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PlayerIsLookingForAGame> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PlayerIsLookingForAGame>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PlayerIsLookingForAGame to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PlayerIsLookingForAGame from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PlayerIsLookingForAGame instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PlayerIsLookingForAGame fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.time.Instant eventTime;
  private java.lang.CharSequence playerId;
  private com.devraccoon.starcraft.domain.game.GameType gameType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PlayerIsLookingForAGame() {}

  /**
   * All-args constructor.
   * @param eventTime The new value for eventTime
   * @param playerId The new value for playerId
   * @param gameType The new value for gameType
   */
  public PlayerIsLookingForAGame(java.time.Instant eventTime, java.lang.CharSequence playerId, com.devraccoon.starcraft.domain.game.GameType gameType) {
    this.eventTime = eventTime.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.playerId = playerId;
    this.gameType = gameType;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventTime;
    case 1: return playerId;
    case 2: return gameType;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventTime = (java.time.Instant)value$; break;
    case 1: playerId = (java.lang.CharSequence)value$; break;
    case 2: gameType = (com.devraccoon.starcraft.domain.game.GameType)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'eventTime' field.
   * @return The value of the 'eventTime' field.
   */
  public java.time.Instant getEventTime() {
    return eventTime;
  }


  /**
   * Sets the value of the 'eventTime' field.
   * @param value the value to set.
   */
  public void setEventTime(java.time.Instant value) {
    this.eventTime = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'playerId' field.
   * @return The value of the 'playerId' field.
   */
  public java.lang.CharSequence getPlayerId() {
    return playerId;
  }


  /**
   * Sets the value of the 'playerId' field.
   * @param value the value to set.
   */
  public void setPlayerId(java.lang.CharSequence value) {
    this.playerId = value;
  }

  /**
   * Gets the value of the 'gameType' field.
   * @return The value of the 'gameType' field.
   */
  public com.devraccoon.starcraft.domain.game.GameType getGameType() {
    return gameType;
  }


  /**
   * Sets the value of the 'gameType' field.
   * @param value the value to set.
   */
  public void setGameType(com.devraccoon.starcraft.domain.game.GameType value) {
    this.gameType = value;
  }

  /**
   * Creates a new PlayerIsLookingForAGame RecordBuilder.
   * @return A new PlayerIsLookingForAGame RecordBuilder
   */
  public static com.devraccoon.starcraft.domain.server.PlayerIsLookingForAGame.Builder newBuilder() {
    return new com.devraccoon.starcraft.domain.server.PlayerIsLookingForAGame.Builder();
  }

  /**
   * Creates a new PlayerIsLookingForAGame RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PlayerIsLookingForAGame RecordBuilder
   */
  public static com.devraccoon.starcraft.domain.server.PlayerIsLookingForAGame.Builder newBuilder(com.devraccoon.starcraft.domain.server.PlayerIsLookingForAGame.Builder other) {
    if (other == null) {
      return new com.devraccoon.starcraft.domain.server.PlayerIsLookingForAGame.Builder();
    } else {
      return new com.devraccoon.starcraft.domain.server.PlayerIsLookingForAGame.Builder(other);
    }
  }

  /**
   * Creates a new PlayerIsLookingForAGame RecordBuilder by copying an existing PlayerIsLookingForAGame instance.
   * @param other The existing instance to copy.
   * @return A new PlayerIsLookingForAGame RecordBuilder
   */
  public static com.devraccoon.starcraft.domain.server.PlayerIsLookingForAGame.Builder newBuilder(com.devraccoon.starcraft.domain.server.PlayerIsLookingForAGame other) {
    if (other == null) {
      return new com.devraccoon.starcraft.domain.server.PlayerIsLookingForAGame.Builder();
    } else {
      return new com.devraccoon.starcraft.domain.server.PlayerIsLookingForAGame.Builder(other);
    }
  }

  /**
   * RecordBuilder for PlayerIsLookingForAGame instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PlayerIsLookingForAGame>
    implements org.apache.avro.data.RecordBuilder<PlayerIsLookingForAGame> {

    private java.time.Instant eventTime;
    private java.lang.CharSequence playerId;
    private com.devraccoon.starcraft.domain.game.GameType gameType;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.devraccoon.starcraft.domain.server.PlayerIsLookingForAGame.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventTime)) {
        this.eventTime = data().deepCopy(fields()[0].schema(), other.eventTime);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.playerId)) {
        this.playerId = data().deepCopy(fields()[1].schema(), other.playerId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.gameType)) {
        this.gameType = data().deepCopy(fields()[2].schema(), other.gameType);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing PlayerIsLookingForAGame instance
     * @param other The existing instance to copy.
     */
    private Builder(com.devraccoon.starcraft.domain.server.PlayerIsLookingForAGame other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.eventTime)) {
        this.eventTime = data().deepCopy(fields()[0].schema(), other.eventTime);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.playerId)) {
        this.playerId = data().deepCopy(fields()[1].schema(), other.playerId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.gameType)) {
        this.gameType = data().deepCopy(fields()[2].schema(), other.gameType);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'eventTime' field.
      * @return The value.
      */
    public java.time.Instant getEventTime() {
      return eventTime;
    }


    /**
      * Sets the value of the 'eventTime' field.
      * @param value The value of 'eventTime'.
      * @return This builder.
      */
    public com.devraccoon.starcraft.domain.server.PlayerIsLookingForAGame.Builder setEventTime(java.time.Instant value) {
      validate(fields()[0], value);
      this.eventTime = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventTime' field has been set.
      * @return True if the 'eventTime' field has been set, false otherwise.
      */
    public boolean hasEventTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventTime' field.
      * @return This builder.
      */
    public com.devraccoon.starcraft.domain.server.PlayerIsLookingForAGame.Builder clearEventTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'playerId' field.
      * @return The value.
      */
    public java.lang.CharSequence getPlayerId() {
      return playerId;
    }


    /**
      * Sets the value of the 'playerId' field.
      * @param value The value of 'playerId'.
      * @return This builder.
      */
    public com.devraccoon.starcraft.domain.server.PlayerIsLookingForAGame.Builder setPlayerId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.playerId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'playerId' field has been set.
      * @return True if the 'playerId' field has been set, false otherwise.
      */
    public boolean hasPlayerId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'playerId' field.
      * @return This builder.
      */
    public com.devraccoon.starcraft.domain.server.PlayerIsLookingForAGame.Builder clearPlayerId() {
      playerId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'gameType' field.
      * @return The value.
      */
    public com.devraccoon.starcraft.domain.game.GameType getGameType() {
      return gameType;
    }


    /**
      * Sets the value of the 'gameType' field.
      * @param value The value of 'gameType'.
      * @return This builder.
      */
    public com.devraccoon.starcraft.domain.server.PlayerIsLookingForAGame.Builder setGameType(com.devraccoon.starcraft.domain.game.GameType value) {
      validate(fields()[2], value);
      this.gameType = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'gameType' field has been set.
      * @return True if the 'gameType' field has been set, false otherwise.
      */
    public boolean hasGameType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'gameType' field.
      * @return This builder.
      */
    public com.devraccoon.starcraft.domain.server.PlayerIsLookingForAGame.Builder clearGameType() {
      gameType = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PlayerIsLookingForAGame build() {
      try {
        PlayerIsLookingForAGame record = new PlayerIsLookingForAGame();
        record.eventTime = fieldSetFlags()[0] ? this.eventTime : (java.time.Instant) defaultValue(fields()[0]);
        record.playerId = fieldSetFlags()[1] ? this.playerId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.gameType = fieldSetFlags()[2] ? this.gameType : (com.devraccoon.starcraft.domain.game.GameType) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PlayerIsLookingForAGame>
    WRITER$ = (org.apache.avro.io.DatumWriter<PlayerIsLookingForAGame>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PlayerIsLookingForAGame>
    READER$ = (org.apache.avro.io.DatumReader<PlayerIsLookingForAGame>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










